package attributes;

public class ClassAttributes extends MethodAttributes {
	public static final String VOLATILE_VARIABLES = "VOLATILE_VARIABLES";
	public static final String PUBLIC_VARIABLES = "PUBLIC_VARIABLES";
	public static final String PRIVATE_VARIABLES = "PRIVATE_VARIABLES";
	public static final String LOCK_OBJECT_FIELDS = "LOCK_OBJECT_FIELDS";
	public static final String CONDITION_OBJECT_FIELDS = "CONDITION_OBJECT_FIELDS";
	public static final String EXECUTOR_OBJECT_FIELDS = "EXECUTOR_OBJECT_FIELDS";
	public static final String CONCURRENTMAP_OBJECT_FIELDS = "CONCURRENTMAP_OBJECT_FIELDS";
	public static final String ATOMICINTEGER_OBJECT_FIELDS = "ATOMICINTEGER_OBJECT_FIELDS";
	public static final String BLOCKINGQUEUE_OBJECT_FIELDS = "BLOCKINGQUEUE_OBJECT_FIELDS";
	public static final String CONCURRENTLINKEDQUEUE_OBJECT_FIELDS = "CONCURRENTLINKEDQUEUE_OBJECT_FIELDS";
	public static final String COPYONWRITEARRAYLIST_OBJECT_FIELDS = "COPYONWRITEARRAYLIST_OBJECT_FIELDS";
	public static final String EXECUTORSERVICE_OBJECT_FIELDS = "EXECUTORSERVICE_OBJECT_FIELDS";
	public static final String FUTURE_OBJECT_FIELDS = "FUTURE_OBJECT_FIELDS";
	public static final String THREADPOOLEXECUTOR_OBJECT_FIELDS = "THREADPOOLEXECUTOR_OBJECT_FIELDS";
	public static final String COUNTDOWNLATCH_OBJECT_FIELDS = "COUNTDOWNLATCH_OBJECT_FIELDS";
	public static final String CYCLICBARRIER_OBJECT_FIELDS = "CYCLICBARRIER_OBJECT_FIELDS";
	public static final String EXCHANGER_OBJECT_FIELDS = "EXCHANGER_OBJECT_FIELDS";
	public static final String SEMAPHORE_OBJECT_FIELDS = "SEMAPHORE_OBJECT_FIELDS";
	public static final String THREADFACTORY_OBJECT_FIELDS = "THREADFACTORY_OBJECT_FIELDS";
	
	public static final String CALLABLE_INTERFACE = "CALLABLE_INTERFACE";
	public static final String DELAYED_INTERFACE = "DELAYED_INTERFACE";
	public static final String THREADFACTORY_INTERFACE = "THREADFACTORY_INTERFACE";
	public static final String BLOCKINGQUEUE_INTERFACE = "BLOCKINGQUEUE_INTERFACE";
	
	public static final String CONCURRENTMAP_OBJECTS_EXTENDS = "CONCURRENTMAP_OBJECTS_EXTENDS";
	public static final String EXECUTORSERVICE_OBJECTS_EXTENDS = "EXECUTORSERVICE_OBJECTS_EXTENDS";
	public static final String THREADPOOLEXECUTOR_OBJECTS_EXTENDS = "THREADPOOLEXECUTOR_OBJECTS_EXTENDS";
	public static final String CYCLICBARRIER_OBJECTS_EXTENDS = "CYCLICBARRIER_OBJECTS_EXTENDS";
	public static final String EXCHANGER_OBJECTS_EXTENDS = "EXCHANGER_OBJECTS_EXTENDS";
	public static final String SEMAPHORE_OBJECTS_EXTENDS = "SEMAPHORE_OBJECTS_EXTENDS";
	public static final String LOCK_OBJECTS_EXTENDS = "LOCK_OBJECTS_EXTENDS";
	public static final String EXECUTOR_OBJECTS_EXTENDS = "EXECUTOR_OBJECTS_EXTENDS";
	public static final String ATOMICINTEGER_OBJECTS_EXTENDS = "ATOMICINTEGER_OBJECTS_EXTENDS";
	public static final String CONCURRENTLINKEDQUEUE_OBJECTS_EXTENDS = "CONCURRENTLINKEDQUEUE_OBJECTS_EXTENDS";
	public static final String COPYONWRITEARRAYLIST_OBJECTS_EXTENDS = "COPYONWRITEARRAYLIST_OBJECTS_EXTENDS";
	public static final String FUTURE_OBJECTS_EXTENDS = "FUTURE_OBJECTS_EXTENDS";
	public static final String COUNTDOWNLATCH_OBJECTS_EXTENDS = "COUNTDOWNLATCH_OBJECTS_EXTENDS";	
}
