///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


#ifndef __Included_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__
#define __Included_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__


#include "jni_base.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     ManualObjectSectionShadowRenderable()
 * Type:       constructor
 * Definition: Ogre::ManualObject::ManualObjectSectionShadowRenderable::ManualObjectSectionShadowRenderable
 * Signature:  (Ogre_ManualObjectOgre_HardwareIndexBufferSharedPtrOgre_VertexDataZZ)V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1_1createManualObjectSectionShadowRenderable_1_1ManualObjectpHardwareIndexBufferSharedPtrpVertexDataPbvbv (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_,  /* class pointer */
  jlong parent, 
  jlong indexBuffer, 
  jlong vertexData, 
  jboolean createSeparateLightCap, 
  jboolean isLightCap
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getWorldTransforms()
 * Type:       virtual method
 * Definition: void Ogre::ManualObject::ManualObjectSectionShadowRenderable::getWorldTransforms
 * Signature:  (Ogre_Matrix4)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getWorldTransforms_1_1Matrix4p_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong xform
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getPositionBuffer()
 * Type:       non-virtual method
 * Definition: HardwareVertexBufferSharedPtr Ogre::ManualObject::ManualObjectSectionShadowRenderable::getPositionBuffer
 * Signature:  ()Ogre_HardwareVertexBufferSharedPtr
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getPositionBuffer (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getWBuffer()
 * Type:       non-virtual method
 * Definition: HardwareVertexBufferSharedPtr Ogre::ManualObject::ManualObjectSectionShadowRenderable::getWBuffer
 * Signature:  ()Ogre_HardwareVertexBufferSharedPtr
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getWBuffer (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     setMaterial()
 * Type:       non-virtual method
 * Definition: void Ogre::ShadowRenderable::setMaterial
 * Signature:  (Ogre_MaterialPtr)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1setMaterial_1_1MaterialPtrR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong mat
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getMaterial()
 * Type:       virtual method
 * Definition: const MaterialPtr& Ogre::ShadowRenderable::getMaterial
 * Signature:  ()Ogre_MaterialPtr
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getMaterial_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getRenderOperation()
 * Type:       virtual method
 * Definition: void Ogre::ShadowRenderable::getRenderOperation
 * Signature:  (Ogre_RenderOperation)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getRenderOperation_1_1RenderOperationr (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong op
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getRenderOperationForUpdate()
 * Type:       non-virtual method
 * Definition: RenderOperation* Ogre::ShadowRenderable::getRenderOperationForUpdate
 * Signature:  ()Ogre_RenderOperation
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getRenderOperationForUpdate (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getSquaredViewDepth()
 * Type:       virtual method
 * Definition: Real Ogre::ShadowRenderable::getSquaredViewDepth
 * Signature:  (Ogre_Camera)float
 */

JNIEXPORT jfloat JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getSquaredViewDepth_1_1CameraP_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong a1
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getLights()
 * Type:       virtual method
 * Definition: const LightList& Ogre::ShadowRenderable::getLights
 * Signature:  ()Ogre_LightList
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getLights_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     isLightCapSeparate()
 * Type:       non-virtual method
 * Definition: bool Ogre::ShadowRenderable::isLightCapSeparate
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1isLightCapSeparate_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getLightCapRenderable()
 * Type:       non-virtual method
 * Definition: ShadowRenderable* Ogre::ShadowRenderable::getLightCapRenderable
 * Signature:  ()Ogre_ShadowRenderable
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getLightCapRenderable (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     isVisible()
 * Type:       virtual method
 * Definition: virtual bool Ogre::ShadowRenderable::isVisible
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1isVisible_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getTechnique()
 * Type:       virtual method
 * Definition: virtual Technique* Ogre::Renderable::getTechnique
 * Signature:  ()Ogre_Technique
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getTechnique_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     preRender()
 * Type:       virtual method
 * Definition: virtual bool Ogre::Renderable::preRender
 * Signature:  (Ogre_SceneManagerOgre_RenderSystem)Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1preRender_1_1SceneManagerpRenderSystemp (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong sm, 
  jlong rsys
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     postRender()
 * Type:       virtual method
 * Definition: virtual void Ogre::Renderable::postRender
 * Signature:  (Ogre_SceneManagerOgre_RenderSystem)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1postRender_1_1SceneManagerpRenderSystemp (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong sm, 
  jlong rsys
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getNumWorldTransforms()
 * Type:       virtual method
 * Definition: virtual unsigned short Ogre::Renderable::getNumWorldTransforms
 * Signature:  ()S
 */

JNIEXPORT jint JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getNumWorldTransforms_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     setUseIdentityProjection()
 * Type:       non-virtual method
 * Definition: void Ogre::Renderable::setUseIdentityProjection
 * Signature:  (Z)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1setUseIdentityProjection_1_1bv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jboolean useIdentityProjection
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getUseIdentityProjection()
 * Type:       non-virtual method
 * Definition: bool Ogre::Renderable::getUseIdentityProjection
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getUseIdentityProjection_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     setUseIdentityView()
 * Type:       non-virtual method
 * Definition: void Ogre::Renderable::setUseIdentityView
 * Signature:  (Z)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1setUseIdentityView_1_1bv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jboolean useIdentityView
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getUseIdentityView()
 * Type:       non-virtual method
 * Definition: bool Ogre::Renderable::getUseIdentityView
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getUseIdentityView_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getCastsShadows()
 * Type:       virtual method
 * Definition: virtual bool Ogre::Renderable::getCastsShadows
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getCastsShadows_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     setCustomParameter()
 * Type:       non-virtual method
 * Definition: void Ogre::Renderable::setCustomParameter
 * Signature:  (IOgre_Vector4)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1setCustomParameter_1_1ivVector4R (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint index, 
  jlong value
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getCustomParameter()
 * Type:       non-virtual method
 * Definition: const Vector4& Ogre::Renderable::getCustomParameter
 * Signature:  (I)Ogre_Vector4
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getCustomParameter_1_1iv_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint index
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     _updateCustomGpuParameter()
 * Type:       virtual method
 * Definition: virtual void Ogre::Renderable::_updateCustomGpuParameter
 * Signature:  (Ogre_GpuProgramParameters_AutoConstantEntryOgre_GpuProgramParameters)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1_1updateCustomGpuParameter_1_1GpuProgramParameters_1AutoConstantEntryRGpuProgramParametersp_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong constantEntry, 
  jlong params
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     setPolygonModeOverrideable()
 * Type:       virtual method
 * Definition: virtual void Ogre::Renderable::setPolygonModeOverrideable
 * Signature:  (Z)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1setPolygonModeOverrideable_1_1bv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jboolean override
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getPolygonModeOverrideable()
 * Type:       virtual method
 * Definition: virtual bool Ogre::Renderable::getPolygonModeOverrideable
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getPolygonModeOverrideable_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     setUserAny()
 * Type:       virtual method
 * Definition: virtual void Ogre::Renderable::setUserAny
 * Signature:  (Ogre_Any)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1setUserAny_1_1AnyR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong anything
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getUserAny()
 * Type:       virtual method
 * Definition: virtual const Any& Ogre::Renderable::getUserAny
 * Signature:  ()Ogre_Any
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getUserAny_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     getRenderSystemData()
 * Type:       virtual method
 * Definition: virtual RenderSystemData* Ogre::Renderable::getRenderSystemData
 * Signature:  ()Ogre_Renderable_RenderSystemData
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1getRenderSystemData_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     setRenderSystemData()
 * Type:       virtual method
 * Definition: virtual void Ogre::Renderable::setRenderSystemData
 * Signature:  (Ogre_Renderable_RenderSystemData)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1setRenderSystemData_1_1RenderSystemDatap_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong val
);

/*
 * Class:      org.ogre4j.ManualObject.00024ManualObjectSectionShadowRenderable
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::ManualObject::ManualObjectSectionShadowRenderable::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /*__Included_org_ogre4j_ManualObject_00024ManualObjectSectionShadowRenderable__*/
