///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


#ifndef __Included_org_ogre4j_Polygon__
#define __Included_org_ogre4j_Polygon__


#include "jni_base.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
 * Class:      org.ogre4j.Polygon
 * Method:     Polygon()
 * Type:       constructor
 * Definition: Ogre::Polygon::Polygon
 * Signature:  ()V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_Polygon__1_1createPolygon (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     Polygon()
 * Type:       constructor
 * Definition: Ogre::Polygon::Polygon
 * Signature:  (Ogre_Polygon)V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_Polygon__1_1createPolygon_1_1PolygonR (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_,  /* class pointer */
  jlong cpy
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     insertVertex()
 * Type:       non-virtual method
 * Definition: void Ogre::Polygon::insertVertex
 * Signature:  (Ogre_Vector3I)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Polygon__1insertVertex_1_1Vector3Riv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong vdata, 
  jint vertexIndex
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     insertVertex()
 * Type:       non-virtual method
 * Definition: void Ogre::Polygon::insertVertex
 * Signature:  (Ogre_Vector3)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Polygon__1insertVertex_1_1Vector3R (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong vdata
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     getVertex()
 * Type:       non-virtual method
 * Definition: const Vector3& Ogre::Polygon::getVertex
 * Signature:  (I)Ogre_Vector3
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_Polygon__1getVertex_1_1iv_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint vertex
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     setVertex()
 * Type:       non-virtual method
 * Definition: void Ogre::Polygon::setVertex
 * Signature:  (Ogre_Vector3I)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Polygon__1setVertex_1_1Vector3Riv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong vdata, 
  jint vertexIndex
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     removeDuplicates()
 * Type:       non-virtual method
 * Definition: void Ogre::Polygon::removeDuplicates
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Polygon__1removeDuplicates (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     getVertexCount()
 * Type:       non-virtual method
 * Definition: size_t Ogre::Polygon::getVertexCount
 * Signature:  ()I
 */

JNIEXPORT jint JNICALL Java_org_ogre4j_Polygon__1getVertexCount_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     getNormal()
 * Type:       non-virtual method
 * Definition: const Vector3& Ogre::Polygon::getNormal
 * Signature:  ()Ogre_Vector3
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_Polygon__1getNormal_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     deleteVertex()
 * Type:       non-virtual method
 * Definition: void Ogre::Polygon::deleteVertex
 * Signature:  (I)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Polygon__1deleteVertex_1_1iv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint vertex
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     isPointInside()
 * Type:       non-virtual method
 * Definition: bool Ogre::Polygon::isPointInside
 * Signature:  (Ogre_Vector3)Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_Polygon__1isPointInside_1_1Vector3R_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong point
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     storeEdges()
 * Type:       non-virtual method
 * Definition: void Ogre::Polygon::storeEdges
 * Signature:  (Ogre_Polygon_EdgeMap)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Polygon__1storeEdges_1_1EdgeMapp_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong edgeMap
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     reset()
 * Type:       non-virtual method
 * Definition: void Ogre::Polygon::reset
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Polygon__1reset (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     operator==()
 * Type:       non-virtual method
 * Definition: bool Ogre::Polygon::operator==
 * Signature:  (Ogre_Polygon)Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_Polygon__1operatorEqual_1_1PolygonR_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong rhs
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     operator!=()
 * Type:       non-virtual method
 * Definition: bool Ogre::Polygon::operator!=
 * Signature:  (Ogre_Polygon)Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_Polygon__1operatorNotEqual_1_1PolygonR_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong rhs
);

/*
 * Class:      org.ogre4j.Polygon
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::Polygon::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Polygon__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /*__Included_org_ogre4j_Polygon__*/
