///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


#ifndef __Included_org_ogre4j_ExternalTextureSource__
#define __Included_org_ogre4j_ExternalTextureSource__


#include "jni_base.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     setInputName()
 * Type:       non-virtual method
 * Definition: void Ogre::ExternalTextureSource::setInputName
 * Signature:  (std_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1setInputName_1_1Stringv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring sIN
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getInputName()
 * Type:       non-virtual method
 * Definition: const String& Ogre::ExternalTextureSource::getInputName
 * Signature:  ()std_string
 */

JNIEXPORT jstring JNICALL Java_org_ogre4j_ExternalTextureSource__1getInputName_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     setFPS()
 * Type:       non-virtual method
 * Definition: void Ogre::ExternalTextureSource::setFPS
 * Signature:  (I)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1setFPS_1_1iv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint iFPS
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getFPS()
 * Type:       non-virtual method
 * Definition: const int Ogre::ExternalTextureSource::getFPS
 * Signature:  ()I
 */

JNIEXPORT jint JNICALL Java_org_ogre4j_ExternalTextureSource__1getFPS_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     setPlayMode()
 * Type:       non-virtual method
 * Definition: void Ogre::ExternalTextureSource::setPlayMode
 * Signature:  (Ogre_eTexturePlayMode)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1setPlayMode_1_1eTexturePlayModev (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint eMode
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getPlayMode()
 * Type:       non-virtual method
 * Definition: eTexturePlayMode Ogre::ExternalTextureSource::getPlayMode
 * Signature:  ()Ogre_eTexturePlayMode
 */

JNIEXPORT jint JNICALL Java_org_ogre4j_ExternalTextureSource__1getPlayMode_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     setTextureTecPassStateLevel()
 * Type:       non-virtual method
 * Definition: void Ogre::ExternalTextureSource::setTextureTecPassStateLevel
 * Signature:  (III)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1setTextureTecPassStateLevel_1_1iviviv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint t, 
  jint p, 
  jint s
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getTextureTecPassStateLevel()
 * Type:       non-virtual method
 * Definition: void Ogre::ExternalTextureSource::getTextureTecPassStateLevel
 * Signature:  (III)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1getTextureTecPassStateLevel_1_1iririr_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong t, 
  jlong p, 
  jlong s
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     addBaseParams()
 * Type:       non-virtual method
 * Definition: void Ogre::ExternalTextureSource::addBaseParams
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1addBaseParams (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getPlugInStringName()
 * Type:       non-virtual method
 * Definition: const String& Ogre::ExternalTextureSource::getPlugInStringName
 * Signature:  ()std_string
 */

JNIEXPORT jstring JNICALL Java_org_ogre4j_ExternalTextureSource__1getPlugInStringName_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getDictionaryStringName()
 * Type:       non-virtual method
 * Definition: const String& Ogre::ExternalTextureSource::getDictionaryStringName
 * Signature:  ()std_string
 */

JNIEXPORT jstring JNICALL Java_org_ogre4j_ExternalTextureSource__1getDictionaryStringName_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     initialise()
 * Type:       pure virtual method
 * Definition: virtual bool Ogre::ExternalTextureSource::initialise
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ExternalTextureSource__1initialise (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     shutDown()
 * Type:       pure virtual method
 * Definition: virtual void Ogre::ExternalTextureSource::shutDown
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1shutDown (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     createDefinedTexture()
 * Type:       pure virtual method
 * Definition: virtual void Ogre::ExternalTextureSource::createDefinedTexture
 * Signature:  (std_stringstd_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1createDefinedTexture_1_1StringRStringR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring sMaterialName, 
  jstring groupName
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     destroyAdvancedTexture()
 * Type:       pure virtual method
 * Definition: virtual void Ogre::ExternalTextureSource::destroyAdvancedTexture
 * Signature:  (std_stringstd_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1destroyAdvancedTexture_1_1StringRStringR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring sTextureName, 
  jstring groupName
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getParamDictionary()
 * Type:       non-virtual method
 * Definition: ParamDictionary* Ogre::StringInterface::getParamDictionary
 * Signature:  ()Ogre_ParamDictionary
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ExternalTextureSource__1getParamDictionary (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getParamDictionary_const()
 * Type:       non-virtual method
 * Definition: const ParamDictionary* Ogre::StringInterface::getParamDictionary
 * Signature:  ()Ogre_ParamDictionary
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ExternalTextureSource__1getParamDictionary_1const_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getParameters()
 * Type:       non-virtual method
 * Definition: const ParameterList& Ogre::StringInterface::getParameters
 * Signature:  ()Ogre_ParameterList
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ExternalTextureSource__1getParameters_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     setParameter()
 * Type:       virtual method
 * Definition: virtual bool Ogre::StringInterface::setParameter
 * Signature:  (std_stringstd_string)Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ExternalTextureSource__1setParameter_1_1StringRStringR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring name, 
  jstring value
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     setParameterList()
 * Type:       virtual method
 * Definition: virtual void Ogre::StringInterface::setParameterList
 * Signature:  (Ogre_NameValuePairList)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1setParameterList_1_1NameValuePairListR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong paramList
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     getParameter()
 * Type:       virtual method
 * Definition: virtual String Ogre::StringInterface::getParameter
 * Signature:  (std_string)std_string
 */

JNIEXPORT jstring JNICALL Java_org_ogre4j_ExternalTextureSource__1getParameter_1_1StringR_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring name
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     copyParametersTo()
 * Type:       virtual method
 * Definition: virtual void Ogre::StringInterface::copyParametersTo
 * Signature:  (Ogre_StringInterface)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1copyParametersTo_1_1StringInterfacep_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong dest
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     cleanupDictionary()
 * Type:       static method
 * Definition: static void Ogre::StringInterface::cleanupDictionary
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1cleanupDictionary (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
);

/*
 * Class:      org.ogre4j.ExternalTextureSource
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::ExternalTextureSource::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ExternalTextureSource__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /*__Included_org_ogre4j_ExternalTextureSource__*/
