///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


#ifndef __Included_org_ogre4j_GpuNamedConstants__
#define __Included_org_ogre4j_GpuNamedConstants__


#include "jni_base.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     generateConstantDefinitionArrayEntries()
 * Type:       non-virtual method
 * Definition: void Ogre::GpuNamedConstants::generateConstantDefinitionArrayEntries
 * Signature:  (std_stringOgre_GpuConstantDefinition)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_GpuNamedConstants__1generateConstantDefinitionArrayEntries_1_1StringRGpuConstantDefinitionR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring paramName, 
  jlong baseDef
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     save()
 * Type:       non-virtual method
 * Definition: void Ogre::GpuNamedConstants::save
 * Signature:  (std_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_GpuNamedConstants__1save_1_1StringR_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring filename
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     load()
 * Type:       non-virtual method
 * Definition: void Ogre::GpuNamedConstants::load
 * Signature:  (Ogre_DataStreamPtr)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_GpuNamedConstants__1load_1_1DataStreamPtrr (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong stream
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     getGenerateAllConstantDefinitionArrayEntries()
 * Type:       static method
 * Definition: static bool Ogre::GpuNamedConstants::getGenerateAllConstantDefinitionArrayEntries
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_GpuNamedConstants__1getGenerateAllConstantDefinitionArrayEntries (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     setGenerateAllConstantDefinitionArrayEntries()
 * Type:       static method
 * Definition: static void Ogre::GpuNamedConstants::setGenerateAllConstantDefinitionArrayEntries
 * Signature:  (Z)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_GpuNamedConstants__1setGenerateAllConstantDefinitionArrayEntries_1_1bv (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_,  /* class pointer */
  jboolean generateAll
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     GpuNamedConstants()
 * Type:       constructor
 * Definition: Ogre::GpuNamedConstants::GpuNamedConstants
 * Signature:  ()V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_GpuNamedConstants__1_1createGpuNamedConstants (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::GpuNamedConstants::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_GpuNamedConstants__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     getfloatBufferSize()
 * Type:       getter for public attribute
 * Definition: size_t Ogre::GpuNamedConstants::floatBufferSize
 * Signature:  ()I
 */

JNIEXPORT jint JNICALL Java_org_ogre4j_GpuNamedConstants__1getfloatBufferSize (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     setfloatBufferSize()
 * Type:       setter for public attribute
 * Definition: size_t Ogre::GpuNamedConstants::floatBufferSize
 * Signature:  (I)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_GpuNamedConstants__1setfloatBufferSize (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint _jni_value_
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     getintBufferSize()
 * Type:       getter for public attribute
 * Definition: size_t Ogre::GpuNamedConstants::intBufferSize
 * Signature:  ()I
 */

JNIEXPORT jint JNICALL Java_org_ogre4j_GpuNamedConstants__1getintBufferSize (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     setintBufferSize()
 * Type:       setter for public attribute
 * Definition: size_t Ogre::GpuNamedConstants::intBufferSize
 * Signature:  (I)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_GpuNamedConstants__1setintBufferSize (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jint _jni_value_
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     getmap()
 * Type:       getter for public attribute
 * Definition: GpuConstantDefinitionMap Ogre::GpuNamedConstants::map
 * Signature:  ()Ogre_GpuConstantDefinitionMap
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_GpuNamedConstants__1getmap (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.GpuNamedConstants
 * Method:     setmap()
 * Type:       setter for public attribute
 * Definition: GpuConstantDefinitionMap Ogre::GpuNamedConstants::map
 * Signature:  (Ogre_GpuConstantDefinitionMap)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_GpuNamedConstants__1setmap (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong _jni_value_
);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /*__Included_org_ogre4j_GpuNamedConstants__*/
