///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


#ifndef __Included_org_ogre4j_ConfigDialog__
#define __Included_org_ogre4j_ConfigDialog__


#include "jni_base.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/*
 * Class:      org.ogre4j.ConfigDialog
 * Method:     ConfigDialog()
 * Type:       constructor
 * Definition: Ogre::ConfigDialog::ConfigDialog
 * Signature:  ()V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ConfigDialog__1_1createConfigDialog (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
);

/*
 * Class:      org.ogre4j.ConfigDialog
 * Method:     display()
 * Type:       non-virtual method
 * Definition: bool Ogre::ConfigDialog::display
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ConfigDialog__1display (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ConfigDialog
 * Method:     initialise()
 * Type:       non-virtual method
 * Definition: void Ogre::ConfigDialog::initialise
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ConfigDialog__1initialise (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ConfigDialog
 * Method:     run()
 * Type:       non-virtual method
 * Definition: void Ogre::ConfigDialog::run
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ConfigDialog__1run (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ConfigDialog
 * Method:     cancel()
 * Type:       non-virtual method
 * Definition: void Ogre::ConfigDialog::cancel
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ConfigDialog__1cancel (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

/*
 * Class:      org.ogre4j.ConfigDialog
 * Method:     windowEventHandler()
 * Type:       static method
 * Definition: static pascal OSStatus Ogre::ConfigDialog::windowEventHandler
 * Signature:  (EventHandlerCallRefEventRefV)pascal_OSStatus
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ConfigDialog__1windowEventHandler_1_1EventHandlerCallRefvEventRefvvp (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_,  /* class pointer */
  jlong aNextHandler, 
  jlong aEvent, 
  jlong aUserData
);

/*
 * Class:      org.ogre4j.ConfigDialog
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::ConfigDialog::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ConfigDialog__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /*__Included_org_ogre4j_ConfigDialog__*/
