///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


// includes from config
#include <Ogre4JStableHeaders.h>

// use base library for cpp2j
#include "jni_base_all.h"

// import declaration of all functions
#include "class_org_ogre4j__1ConfigOption.h"

// import header files of original library
#include <OgreConfigOptionMap.h>



/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     _ConfigOption()
 * Type:       constructor
 * Definition: Ogre::_ConfigOption::_ConfigOption
 * Signature:  ()V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j__1ConfigOption__1_1create_1ConfigOption (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
)
{
   // constructor of class Ogre::_ConfigOption 
   
   // parameter conversions 
   
   // create new instance of class Ogre::_ConfigOption 
   Ogre::_ConfigOption* _cpp_this = new Ogre::_ConfigOption(); 
   
   // return casted pointer 
   jlong _jni_pointer_ = reinterpret_cast<jlong>(_cpp_this); 
   return _jni_pointer_;
} /* Ogre::_ConfigOption::_ConfigOption */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::_ConfigOption::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j__1ConfigOption__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // destructor of class Ogre::_ConfigOption 
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this = reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   // delete object if it exists 
   if(_cpp_this != NULL) delete _cpp_this;
} /* Ogre::_ConfigOption::__delete */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     getname()
 * Type:       getter for public attribute
 * Definition: String Ogre::_ConfigOption::name
 * Signature:  ()std_string
 */

JNIEXPORT jstring JNICALL Java_org_ogre4j__1ConfigOption__1getname (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this = reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   
   // call library method 
   const std::string _cpp_result = _cpp_this->name; 
   return org::xbig::jni::to_jstring(_jni_env_, _cpp_result);
} /* String Ogre::_ConfigOption::name */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     setname()
 * Type:       setter for public attribute
 * Definition: String Ogre::_ConfigOption::name
 * Signature:  (std_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j__1ConfigOption__1setname (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring _jni_value_
)
{
   // parameter conversions 
  std::string _cpp__jni_value_ = ""; org::xbig::jni::to_stdstring(_jni_env_, _jni_value_, _cpp__jni_value_); // calls c-tor only. Not operator= .; 
   
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this =reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->name = _cpp__jni_value_;
} /* String Ogre::_ConfigOption::name */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     getcurrentValue()
 * Type:       getter for public attribute
 * Definition: String Ogre::_ConfigOption::currentValue
 * Signature:  ()std_string
 */

JNIEXPORT jstring JNICALL Java_org_ogre4j__1ConfigOption__1getcurrentValue (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this = reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   
   // call library method 
   const std::string _cpp_result = _cpp_this->currentValue; 
   return org::xbig::jni::to_jstring(_jni_env_, _cpp_result);
} /* String Ogre::_ConfigOption::currentValue */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     setcurrentValue()
 * Type:       setter for public attribute
 * Definition: String Ogre::_ConfigOption::currentValue
 * Signature:  (std_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j__1ConfigOption__1setcurrentValue (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring _jni_value_
)
{
   // parameter conversions 
  std::string _cpp__jni_value_ = ""; org::xbig::jni::to_stdstring(_jni_env_, _jni_value_, _cpp__jni_value_); // calls c-tor only. Not operator= .; 
   
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this =reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->currentValue = _cpp__jni_value_;
} /* String Ogre::_ConfigOption::currentValue */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     getpossibleValues()
 * Type:       getter for public attribute
 * Definition: StringVector Ogre::_ConfigOption::possibleValues
 * Signature:  ()Ogre_StringVector
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j__1ConfigOption__1getpossibleValues (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this = reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::StringVector* _cpp_result = new Ogre::StringVector( _cpp_this->possibleValues); 
   return reinterpret_cast<jlong>(_cpp_result);
} /* StringVector Ogre::_ConfigOption::possibleValues */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     setpossibleValues()
 * Type:       setter for public attribute
 * Definition: StringVector Ogre::_ConfigOption::possibleValues
 * Signature:  (Ogre_StringVector)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j__1ConfigOption__1setpossibleValues (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong _jni_value_
)
{
   // parameter conversions 
  Ogre::StringVector* _cpp__jni_value_ = reinterpret_cast< Ogre::StringVector* >(_jni_value_); 
   
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this =reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->possibleValues = *_cpp__jni_value_;
} /* StringVector Ogre::_ConfigOption::possibleValues */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     getimmutable()
 * Type:       getter for public attribute
 * Definition: bool Ogre::_ConfigOption::immutable
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j__1ConfigOption__1getimmutable (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this = reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   
   // call library method 
   const bool _cpp_result = _cpp_this->immutable; 
   return _cpp_result ? 1 : 0;
} /* bool Ogre::_ConfigOption::immutable */


/*
 * Class:      org.ogre4j..1ConfigOption
 * Method:     setimmutable()
 * Type:       setter for public attribute
 * Definition: bool Ogre::_ConfigOption::immutable
 * Signature:  (Z)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j__1ConfigOption__1setimmutable (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jboolean _jni_value_
)
{
   // parameter conversions 
  bool _cpp__jni_value_ = _jni_value_ ? true : false; 
   
   // cast pointer to C++ object 
   Ogre::_ConfigOption* _cpp_this =reinterpret_cast<Ogre::_ConfigOption*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->immutable = _cpp__jni_value_;
} /* bool Ogre::_ConfigOption::immutable */
