///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


// includes from config
#include <Ogre4JStableHeaders.h>

// use base library for cpp2j
#include "jni_base_all.h"

// import declaration of all functions
#include "class_org_ogre4j_MaterialSerializer.h"

// import header files of original library
#include <OgreMaterialSerializer.h>



/*
 * Class:      org.ogre4j.MaterialSerializer
 * Method:     MaterialSerializer()
 * Type:       constructor
 * Definition: Ogre::MaterialSerializer::MaterialSerializer
 * Signature:  ()V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_MaterialSerializer__1_1createMaterialSerializer (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
)
{
   // constructor of class Ogre::MaterialSerializer 
   
   // parameter conversions 
   
   // create new instance of class Ogre::MaterialSerializer 
   Ogre::MaterialSerializer* _cpp_this = new Ogre::MaterialSerializer(); 
   
   // return casted pointer 
   jlong _jni_pointer_ = reinterpret_cast<jlong>(_cpp_this); 
   return _jni_pointer_;
} /* Ogre::MaterialSerializer::MaterialSerializer */


/*
 * Class:      org.ogre4j.MaterialSerializer
 * Method:     queueForExport()
 * Type:       non-virtual method
 * Definition: void Ogre::MaterialSerializer::queueForExport
 * Signature:  (Ogre_MaterialPtrZZ)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_MaterialSerializer__1queueForExport_1_1MaterialPtrRbvbv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong pMat, 
  jboolean clearQueued, 
  jboolean exportDefaults
)
{
   // parameter conversions 
  const Ogre::MaterialPtr* _cpp_pMat = reinterpret_cast< const Ogre::MaterialPtr* >(pMat);
  bool _cpp_clearQueued = clearQueued ? true : false;
  bool _cpp_exportDefaults = exportDefaults ? true : false; 
   
   // cast pointer to C++ object 
   Ogre::MaterialSerializer* _cpp_this = reinterpret_cast<Ogre::MaterialSerializer*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->queueForExport(*_cpp_pMat, _cpp_clearQueued, _cpp_exportDefaults);
} /* void Ogre::MaterialSerializer::queueForExport */


/*
 * Class:      org.ogre4j.MaterialSerializer
 * Method:     exportQueued()
 * Type:       non-virtual method
 * Definition: void Ogre::MaterialSerializer::exportQueued
 * Signature:  (std_stringZstd_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_MaterialSerializer__1exportQueued_1_1StringRbVStringR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jstring filename, 
  jboolean includeProgDef, 
  jstring programFilename
)
{
   // parameter conversions 
  std::string _cpp_filename = ""; org::xbig::jni::to_stdstring(_jni_env_, filename, _cpp_filename); // calls c-tor only. Not operator= .;
  const bool _cpp_includeProgDef = includeProgDef ? true : false;
  std::string _cpp_programFilename = ""; org::xbig::jni::to_stdstring(_jni_env_, programFilename, _cpp_programFilename); // calls c-tor only. Not operator= .; 
   
   // cast pointer to C++ object 
   Ogre::MaterialSerializer* _cpp_this = reinterpret_cast<Ogre::MaterialSerializer*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->exportQueued(_cpp_filename, _cpp_includeProgDef, _cpp_programFilename);
} /* void Ogre::MaterialSerializer::exportQueued */


/*
 * Class:      org.ogre4j.MaterialSerializer
 * Method:     exportMaterial()
 * Type:       non-virtual method
 * Definition: void Ogre::MaterialSerializer::exportMaterial
 * Signature:  (Ogre_MaterialPtrstd_stringZZstd_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_MaterialSerializer__1exportMaterial_1_1MaterialPtrRStringRbvbVStringR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong pMat, 
  jstring filename, 
  jboolean exportDefaults, 
  jboolean includeProgDef, 
  jstring programFilename
)
{
   // parameter conversions 
  const Ogre::MaterialPtr* _cpp_pMat = reinterpret_cast< const Ogre::MaterialPtr* >(pMat);
  std::string _cpp_filename = ""; org::xbig::jni::to_stdstring(_jni_env_, filename, _cpp_filename); // calls c-tor only. Not operator= .;
  bool _cpp_exportDefaults = exportDefaults ? true : false;
  const bool _cpp_includeProgDef = includeProgDef ? true : false;
  std::string _cpp_programFilename = ""; org::xbig::jni::to_stdstring(_jni_env_, programFilename, _cpp_programFilename); // calls c-tor only. Not operator= .; 
   
   // cast pointer to C++ object 
   Ogre::MaterialSerializer* _cpp_this = reinterpret_cast<Ogre::MaterialSerializer*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->exportMaterial(*_cpp_pMat, _cpp_filename, _cpp_exportDefaults, _cpp_includeProgDef, _cpp_programFilename);
} /* void Ogre::MaterialSerializer::exportMaterial */


/*
 * Class:      org.ogre4j.MaterialSerializer
 * Method:     getQueuedAsString()
 * Type:       non-virtual method
 * Definition: const String& Ogre::MaterialSerializer::getQueuedAsString
 * Signature:  ()std_string
 */

JNIEXPORT jstring JNICALL Java_org_ogre4j_MaterialSerializer__1getQueuedAsString_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::MaterialSerializer* _cpp_this = reinterpret_cast<const Ogre::MaterialSerializer*>(_jni_pointer_); 
   
   // call library method 
   std::string _cpp_result = _cpp_this->getQueuedAsString() ; 
   return org::xbig::jni::to_jstring(_jni_env_, _cpp_result);
} /* const String& Ogre::MaterialSerializer::getQueuedAsString */


/*
 * Class:      org.ogre4j.MaterialSerializer
 * Method:     clearQueue()
 * Type:       non-virtual method
 * Definition: void Ogre::MaterialSerializer::clearQueue
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_MaterialSerializer__1clearQueue (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::MaterialSerializer* _cpp_this = reinterpret_cast<Ogre::MaterialSerializer*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->clearQueue();
} /* void Ogre::MaterialSerializer::clearQueue */


/*
 * Class:      org.ogre4j.MaterialSerializer
 * Method:     parseScript()
 * Type:       non-virtual method
 * Definition: void Ogre::MaterialSerializer::parseScript
 * Signature:  (Ogre_DataStreamPtrstd_string)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_MaterialSerializer__1parseScript_1_1DataStreamPtrrStringR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong stream, 
  jstring groupName
)
{
   // parameter conversions 
  Ogre::DataStreamPtr* _cpp_stream = reinterpret_cast< Ogre::DataStreamPtr* >(stream);
  std::string _cpp_groupName = ""; org::xbig::jni::to_stdstring(_jni_env_, groupName, _cpp_groupName); // calls c-tor only. Not operator= .; 
   
   // cast pointer to C++ object 
   Ogre::MaterialSerializer* _cpp_this = reinterpret_cast<Ogre::MaterialSerializer*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->parseScript(*_cpp_stream, _cpp_groupName);
} /* void Ogre::MaterialSerializer::parseScript */


/*
 * Class:      org.ogre4j.MaterialSerializer
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::MaterialSerializer::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_MaterialSerializer__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // destructor of class Ogre::MaterialSerializer 
   // cast pointer to C++ object 
   Ogre::MaterialSerializer* _cpp_this = reinterpret_cast<Ogre::MaterialSerializer*>(_jni_pointer_); 
   // delete object if it exists 
   if(_cpp_this != NULL) delete _cpp_this;
} /* Ogre::MaterialSerializer::__delete */
