///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


// includes from config
#include <Ogre4JStableHeaders.h>

// use base library for cpp2j
#include "jni_base_all.h"

// import declaration of all functions
#include "class_org_ogre4j_ScriptTokenListPtr.h"

// import header files of original library
#include <OgreSharedPtr.h>
#include "OgreScriptLexer.h"



/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     ScriptTokenListPtr()
 * Type:       constructor
 * Definition: Ogre::SharedPtr< T >::SharedPtr
 * Signature:  ()V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ScriptTokenListPtr__1_1createScriptTokenListPtr (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
)
{
   // constructor of class Ogre::ScriptTokenListPtr 
   
   // parameter conversions 
   
   // create new instance of class Ogre::ScriptTokenListPtr 
   Ogre::ScriptTokenListPtr* _cpp_this = new Ogre::ScriptTokenListPtr(); 
   
   // return casted pointer 
   jlong _jni_pointer_ = reinterpret_cast<jlong>(_cpp_this); 
   return _jni_pointer_;
} /* Ogre::SharedPtr< T >::SharedPtr */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     operator=()
 * Type:       non-virtual method
 * Definition: SharedPtr& Ogre::SharedPtr< T >::operator=
 * Signature:  (Ogre_SharedPtr)Ogre_SharedPtr
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ScriptTokenListPtr__1operatorAssignment_1_1_1Ogre_1SharedPtrR (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong r
)
{
   // parameter conversions 
  const Ogre::ScriptTokenListPtr* _cpp_r = reinterpret_cast< const Ogre::ScriptTokenListPtr* >(r); 
   
   // cast pointer to C++ object 
   Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::ScriptTokenListPtr* _cpp_result = & _cpp_this->operator=(*_cpp_r) ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* SharedPtr& Ogre::SharedPtr< T >::operator= */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     operator *()
 * Type:       non-virtual method
 * Definition: T& Ogre::SharedPtr< T >::operator *
 * Signature:  ()Ogre_ScriptTokenList
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ScriptTokenListPtr__1operatorMultiplication_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::ScriptTokenList* _cpp_result = & _cpp_this->operator *() ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* T& Ogre::SharedPtr< T >::operator * */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     operator->()
 * Type:       non-virtual method
 * Definition: T* Ogre::SharedPtr< T >::operator->
 * Signature:  ()Ogre_ScriptTokenList
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ScriptTokenListPtr__1operatorMemberAccessFromAPointer_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::ScriptTokenList* _cpp_result = _cpp_this->operator->() ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* T* Ogre::SharedPtr< T >::operator-> */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     get()
 * Type:       non-virtual method
 * Definition: T* Ogre::SharedPtr< T >::get
 * Signature:  ()Ogre_ScriptTokenList
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ScriptTokenListPtr__1get_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::ScriptTokenList* _cpp_result = _cpp_this->get() ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* T* Ogre::SharedPtr< T >::get */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     bind()
 * Type:       non-virtual method
 * Definition: void Ogre::SharedPtr< T >::bind
 * Signature:  (Ogre_ScriptTokenListOgre_SharedPtrFreeMethod)V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ScriptTokenListPtr__1bind_1_1Ogre_1ScriptTokenListp_1Ogre_1SharedPtrFreeMethodv (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong rep, 
  jint freeMethod
)
{
   // parameter conversions 
  Ogre::ScriptTokenList* _cpp_rep = reinterpret_cast< Ogre::ScriptTokenList* >(rep);
  Ogre::SharedPtrFreeMethod _cpp_freeMethod = (Ogre::SharedPtrFreeMethod)freeMethod; 
   
   // cast pointer to C++ object 
   Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->bind(_cpp_rep, _cpp_freeMethod);
} /* void Ogre::SharedPtr< T >::bind */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     unique()
 * Type:       non-virtual method
 * Definition: bool Ogre::SharedPtr< T >::unique
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ScriptTokenListPtr__1unique_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const bool _cpp_result = _cpp_this->unique() ; 
   return _cpp_result ? 1 : 0;
} /* bool Ogre::SharedPtr< T >::unique */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     useCount()
 * Type:       non-virtual method
 * Definition: unsigned int Ogre::SharedPtr< T >::useCount
 * Signature:  ()I
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ScriptTokenListPtr__1useCount_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const unsigned int _cpp_result = _cpp_this->useCount() ; 
   return _cpp_result;
} /* unsigned int Ogre::SharedPtr< T >::useCount */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     useCountPointer()
 * Type:       non-virtual method
 * Definition: unsigned int* Ogre::SharedPtr< T >::useCountPointer
 * Signature:  ()I
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ScriptTokenListPtr__1useCountPointer_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   unsigned int* _cpp_result = _cpp_this->useCountPointer() ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* unsigned int* Ogre::SharedPtr< T >::useCountPointer */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     getPointer()
 * Type:       non-virtual method
 * Definition: T* Ogre::SharedPtr< T >::getPointer
 * Signature:  ()Ogre_ScriptTokenList
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ScriptTokenListPtr__1getPointer_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::ScriptTokenList* _cpp_result = _cpp_this->getPointer() ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* T* Ogre::SharedPtr< T >::getPointer */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     freeMethod()
 * Type:       non-virtual method
 * Definition: SharedPtrFreeMethod Ogre::SharedPtr< T >::freeMethod
 * Signature:  ()Ogre_SharedPtrFreeMethod
 */

JNIEXPORT jint JNICALL Java_org_ogre4j_ScriptTokenListPtr__1freeMethod_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::SharedPtrFreeMethod _cpp_result = _cpp_this->freeMethod() ; 
   return _cpp_result;
} /* SharedPtrFreeMethod Ogre::SharedPtr< T >::freeMethod */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     isNull()
 * Type:       non-virtual method
 * Definition: bool Ogre::SharedPtr< T >::isNull
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ScriptTokenListPtr__1isNull_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<const Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   const bool _cpp_result = _cpp_this->isNull() ; 
   return _cpp_result ? 1 : 0;
} /* bool Ogre::SharedPtr< T >::isNull */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     setNull()
 * Type:       non-virtual method
 * Definition: void Ogre::SharedPtr< T >::setNull
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ScriptTokenListPtr__1setNull (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->setNull();
} /* void Ogre::SharedPtr< T >::setNull */


/*
 * Class:      org.ogre4j.ScriptTokenListPtr
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::ScriptTokenListPtr::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ScriptTokenListPtr__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // destructor of class Ogre::ScriptTokenListPtr 
   // cast pointer to C++ object 
   Ogre::ScriptTokenListPtr* _cpp_this = reinterpret_cast<Ogre::ScriptTokenListPtr*>(_jni_pointer_); 
   // delete object if it exists 
   if(_cpp_this != NULL) delete _cpp_this;
} /* Ogre::ScriptTokenListPtr::__delete */
