/**
 *  This source file is generated by XBiG (The XSLT Bindings Generator)
 *  For the latest info, see http://sourceforge.net/projects/xbig/
 * 
 *  Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
 *  Also see acknowledgements in Readme.html
 * 
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU Lesser General Public License as published by the Free Software
 *  Foundation; either version 2 of the License, or (at your option) any later
 *  version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License along with
 *  this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 *  Place - Suite 330, Boston, MA 02111-1307, USA, or go to
 *  http://www.gnu.org/copyleft/lesser.txt.
 * 
 *  Machine generated file
 */

        

package org.ogre4j;


import org.xbig.base.*;
public interface IRadian extends INativeObject {

    /** **/
    public org.ogre4j.IRadian operatorAssignment(float f);

    /** **/
    public org.ogre4j.IRadian operatorAssignment(org.ogre4j.IRadian r);

    /** **/
    public org.ogre4j.IRadian operatorAssignment(org.ogre4j.IDegree d);

    /** **/
    public float valueDegrees();

    /** **/
    public float valueRadians();

    /** **/
    public float valueAngleUnits();

    /** **/
    public org.ogre4j.IRadian operatorAddition();

    /** **/
    public void operatorAddition(org.ogre4j.IRadian returnValue, org.ogre4j.IRadian r);

    /** **/
    public void operatorAddition(org.ogre4j.IRadian returnValue, org.ogre4j.IDegree d);

    /** **/
    public org.ogre4j.IRadian operatorIncrementAndAssign(org.ogre4j.IRadian r);

    /** **/
    public org.ogre4j.IRadian operatorIncrementAndAssign(org.ogre4j.IDegree d);

    /** **/
    public void operatorSubtraction(org.ogre4j.IRadian returnValue);

    /** **/
    public void operatorSubtraction(org.ogre4j.IRadian returnValue, org.ogre4j.IRadian r);

    /** **/
    public void operatorSubtraction(org.ogre4j.IRadian returnValue, org.ogre4j.IDegree d);

    /** **/
    public org.ogre4j.IRadian operatorDecrementAndAssign(org.ogre4j.IRadian r);

    /** **/
    public org.ogre4j.IRadian operatorDecrementAndAssign(org.ogre4j.IDegree d);

    /** **/
    public void operatorMultiplication(org.ogre4j.IRadian returnValue, float f);

    /** **/
    public void operatorMultiplication(org.ogre4j.IRadian returnValue, org.ogre4j.IRadian f);

    /** **/
    public org.ogre4j.IRadian operatorMultiplyAndAssign(float f);

    /** **/
    public void operatorDivision(org.ogre4j.IRadian returnValue, float f);

    /** **/
    public org.ogre4j.IRadian operatorDivideAndAssign(float f);

    /** **/
    public boolean operatorLessThan(org.ogre4j.IRadian r);

    /** **/
    public boolean operatorLessThanOrEqual(org.ogre4j.IRadian r);

    /** **/
    public boolean operatorEqual(org.ogre4j.IRadian r);

    /** **/
    public boolean operatorNotEqual(org.ogre4j.IRadian r);

    /** **/
    public boolean operatorGreaterThanOrEqual(org.ogre4j.IRadian r);

    /** **/
    public boolean operatorGreaterThan(org.ogre4j.IRadian r);

}
