/**
 *  This source file is generated by XBiG (The XSLT Bindings Generator)
 *  For the latest info, see http://sourceforge.net/projects/xbig/
 * 
 *  Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
 *  Also see acknowledgements in Readme.html
 * 
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU Lesser General Public License as published by the Free Software
 *  Foundation; either version 2 of the License, or (at your option) any later
 *  version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License along with
 *  this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 *  Place - Suite 330, Boston, MA 02111-1307, USA, or go to
 *  http://www.gnu.org/copyleft/lesser.txt.
 * 
 *  Machine generated file
 */

        

package org.ogre4j;


import org.xbig.base.*;
public class SceneQueryMovableObjectPair extends org.xbig.base.NativeObject implements org.ogre4j.ISceneQueryMovableObjectPair {
static { System.loadLibrary("ogre4j");}
 
        
	/**
	 * 
	 * This constructor is public for internal useage only!
	 * Do not use it!
	 * 
	 */
	public SceneQueryMovableObjectPair(org.xbig.base.InstancePointer p) {
		super(p);
	}

	/**
	 * 
	 * Creates a Java wrapper object for an existing C++ object.
	 * If remote is set to 'true' this object cannot be deleted in Java.
	 * 
	 */
	protected SceneQueryMovableObjectPair(org.xbig.base.InstancePointer p, boolean remote) {
		super(p, remote);
	}

    /**
     * Allows creation of Java objects without C++ objects.
     * 
     * @see org.xbig.base.WithoutNativeObject
     * @see org.xbig.base.INativeObject#disconnectFromNativeObject()
     */
	public SceneQueryMovableObjectPair(org.xbig.base.WithoutNativeObject val) {
		super(val);
	}

	public void delete() {
		if (this.remote) {
	       throw new RuntimeException("can't dispose object created by native library");
	    }

		if(!this.deleted) {
		    __delete(object.pointer);
		    this.deleted = true;
		   	this.object.pointer = 0;
		}
	}

	public void finalize() {
		if(!this.remote && !this.deleted) {
			delete();
		}
	}
	
			
	private final native void __delete(long _pointer_);	



          /** **/
    public org.ogre4j.IMovableObject getfirst() {
         return new org.ogre4j.MovableObject(new InstancePointer(_getfirst(this.object.pointer)));
    }

    private native long _getfirst(long _pointer_);

    /** **/
    public void setfirst(org.ogre4j.IMovableObject _jni_value_) {
        _setfirst(this.object.pointer, _jni_value_.getInstancePointer().pointer);
    }

    private native void _setfirst(long _pointer_, long _jni_value_);

    /** **/
    public org.ogre4j.IMovableObject getsecond() {
         return new org.ogre4j.MovableObject(new InstancePointer(_getsecond(this.object.pointer)));
    }

    private native long _getsecond(long _pointer_);

    /** **/
    public void setsecond(org.ogre4j.IMovableObject _jni_value_) {
        _setsecond(this.object.pointer, _jni_value_.getInstancePointer().pointer);
    }

    private native void _setsecond(long _pointer_, long _jni_value_);

}
