///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


// includes from config
#include <Ogre4JStableHeaders.h>

// use base library for cpp2j
#include "jni_base_all.h"

// import declaration of all functions
#include "class_org_ogre4j_ArchiveManager_00024ArchiveMapIterator.h"

// import header files of original library
#include <OgreIteratorWrappers.h>
#include <OgreArchiveManager.h>



/*
 * Class:      org.ogre4j.ArchiveManager.00024ArchiveMapIterator
 * Method:     hasMoreElements()
 * Type:       non-virtual method
 * Definition: bool Ogre::MapIterator< T >::hasMoreElements
 * Signature:  ()Z
 */

JNIEXPORT jboolean JNICALL Java_org_ogre4j_ArchiveManager_00024ArchiveMapIterator__1hasMoreElements_1const (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   const Ogre::ArchiveManager::ArchiveMapIterator* _cpp_this = reinterpret_cast<const Ogre::ArchiveManager::ArchiveMapIterator*>(_jni_pointer_); 
   
   // call library method 
   const bool _cpp_result = _cpp_this->hasMoreElements() ; 
   return _cpp_result ? 1 : 0;
} /* bool Ogre::MapIterator< T >::hasMoreElements */


/*
 * Class:      org.ogre4j.ArchiveManager.00024ArchiveMapIterator
 * Method:     getNext()
 * Type:       non-virtual method
 * Definition: T::mapped_type Ogre::MapIterator< T >::getNext
 * Signature:  ()Ogre_Archive
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ArchiveManager_00024ArchiveMapIterator__1getNext (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::ArchiveManager::ArchiveMapIterator* _cpp_this = reinterpret_cast<Ogre::ArchiveManager::ArchiveMapIterator*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::Archive* _cpp_result = _cpp_this->getNext() ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* T::mapped_type Ogre::MapIterator< T >::getNext */


/*
 * Class:      org.ogre4j.ArchiveManager.00024ArchiveMapIterator
 * Method:     peekNextValue()
 * Type:       non-virtual method
 * Definition: T::mapped_type Ogre::MapIterator< T >::peekNextValue
 * Signature:  ()Ogre_Archive
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ArchiveManager_00024ArchiveMapIterator__1peekNextValue (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::ArchiveManager::ArchiveMapIterator* _cpp_this = reinterpret_cast<Ogre::ArchiveManager::ArchiveMapIterator*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::Archive* _cpp_result = _cpp_this->peekNextValue() ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* T::mapped_type Ogre::MapIterator< T >::peekNextValue */


/*
 * Class:      org.ogre4j.ArchiveManager.00024ArchiveMapIterator
 * Method:     peekNextKey()
 * Type:       non-virtual method
 * Definition: T::key_type Ogre::MapIterator< T >::peekNextKey
 * Signature:  ()Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL Java_org_ogre4j_ArchiveManager_00024ArchiveMapIterator__1peekNextKey (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::ArchiveManager::ArchiveMapIterator* _cpp_this = reinterpret_cast<Ogre::ArchiveManager::ArchiveMapIterator*>(_jni_pointer_); 
   
   // call library method 
   const std::string _cpp_result = _cpp_this->peekNextKey() ; 
   return org::xbig::jni::to_jstring(_jni_env_, _cpp_result);
} /* T::key_type Ogre::MapIterator< T >::peekNextKey */


/*
 * Class:      org.ogre4j.ArchiveManager.00024ArchiveMapIterator
 * Method:     operator=()
 * Type:       non-virtual method
 * Definition: MapIterator<T>& Ogre::MapIterator< T >::operator=
 * Signature:  (Ogre_ArchiveManager_ArchiveMapIterator)Ogre_ArchiveManager_ArchiveMapIterator
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ArchiveManager_00024ArchiveMapIterator__1operatorAssignment_1_1_1Ogre_1ArchiveManager_1ArchiveMapIteratorr (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_, /* C++ pointer */
  jlong rhs
)
{
   // parameter conversions 
  Ogre::ArchiveManager::ArchiveMapIterator* _cpp_rhs = reinterpret_cast< Ogre::ArchiveManager::ArchiveMapIterator* >(rhs); 
   
   // cast pointer to C++ object 
   Ogre::ArchiveManager::ArchiveMapIterator* _cpp_this = reinterpret_cast<Ogre::ArchiveManager::ArchiveMapIterator*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::ArchiveManager::ArchiveMapIterator* _cpp_result = & _cpp_this->operator=(*_cpp_rhs) ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* MapIterator<T>& Ogre::MapIterator< T >::operator= */


/*
 * Class:      org.ogre4j.ArchiveManager.00024ArchiveMapIterator
 * Method:     peekNextValuePtr()
 * Type:       non-virtual method
 * Definition: T::mapped_type* Ogre::MapIterator< T >::peekNextValuePtr
 * Signature:  ()Ogre_Archive
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_ArchiveManager_00024ArchiveMapIterator__1peekNextValuePtr (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::ArchiveManager::ArchiveMapIterator* _cpp_this = reinterpret_cast<Ogre::ArchiveManager::ArchiveMapIterator*>(_jni_pointer_); 
   
   // call library method 
   const Ogre::Archive* const * _cpp_result = _cpp_this->peekNextValuePtr() ; 
   return reinterpret_cast<jlong>(_cpp_result);
} /* T::mapped_type* Ogre::MapIterator< T >::peekNextValuePtr */


/*
 * Class:      org.ogre4j.ArchiveManager.00024ArchiveMapIterator
 * Method:     moveNext()
 * Type:       non-virtual method
 * Definition: void Ogre::MapIterator< T >::moveNext
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ArchiveManager_00024ArchiveMapIterator__1moveNext (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // parameter conversions 
   
   // cast pointer to C++ object 
   Ogre::ArchiveManager::ArchiveMapIterator* _cpp_this = reinterpret_cast<Ogre::ArchiveManager::ArchiveMapIterator*>(_jni_pointer_); 
   
   // call library method 
   _cpp_this->moveNext();
} /* void Ogre::MapIterator< T >::moveNext */


/*
 * Class:      org.ogre4j.ArchiveManager.00024ArchiveMapIterator
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::ArchiveManager::ArchiveMapIterator::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_ArchiveManager_00024ArchiveMapIterator__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // destructor of class Ogre::ArchiveManager::ArchiveMapIterator 
   // cast pointer to C++ object 
   Ogre::ArchiveManager::ArchiveMapIterator* _cpp_this = reinterpret_cast<Ogre::ArchiveManager::ArchiveMapIterator*>(_jni_pointer_); 
   // delete object if it exists 
   if(_cpp_this != NULL) delete _cpp_this;
} /* Ogre::ArchiveManager::ArchiveMapIterator::__delete */
