///////////////////////////////////////////////////////////////////////////////
/// This source file is generated by XBiG (The XSLT Bindings Generator)
/// For the latest info, see http://sourceforge.net/projects/xbig/
///
/// Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
/// Also see acknowledgements in Readme.html
///
/// This program is free software; you can redistribute it and/or modify it under
/// the terms of the GNU Lesser General Public License as published by the Free Software
/// Foundation; either version 2 of the License, or (at your option) any later
/// version.
///
/// This program is distributed in the hope that it will be useful, but WITHOUT
/// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
/// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
///
/// You should have received a copy of the GNU Lesser General Public License along with
/// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
/// Place - Suite 330, Boston, MA 02111-1307, USA, or go to
/// http://www.gnu.org/copyleft/lesser.txt.
///
/// Machine generated file
///////////////////////////////////////////////////////////////////////////////



#ifdef WIN32
	// disable warnings
	#pragma warning (disable : 4267) // conversion from 'size_t' to 'jint'
#else

#endif


// includes from config
#include <Ogre4JStableHeaders.h>

// use base library for cpp2j
#include "jni_base_all.h"

// import declaration of all functions
#include "class_org_ogre4j_Log_00024Stream_00024Flush.h"

// import header files of original library
#include <OgreLog.h>



/*
 * Class:      org.ogre4j.Log.00024Stream.00024Flush
 * Method:     Flush()
 * Type:       constructor
 * Definition: Ogre::Log::Stream::Flush::Flush
 * Signature:  ()V
 */

JNIEXPORT jlong JNICALL Java_org_ogre4j_Log_00024Stream_00024Flush__1_1createFlush (
  JNIEnv* _jni_env_, /* interface pointer */
  jclass _jni_class_  /* class pointer */
)
{
   // constructor of class Ogre::Log::Stream::Flush 
   
   // parameter conversions 
   
   // create new instance of class Ogre::Log::Stream::Flush 
   Ogre::Log::Stream::Flush* _cpp_this = new Ogre::Log::Stream::Flush(); 
   
   // return casted pointer 
   jlong _jni_pointer_ = reinterpret_cast<jlong>(_cpp_this); 
   return _jni_pointer_;
} /* Ogre::Log::Stream::Flush::Flush */


/*
 * Class:      org.ogre4j.Log.00024Stream.00024Flush
 * Method:     __delete()
 * Type:       destructor
 * Definition: Ogre::Log::Stream::Flush::__delete
 * Signature:  ()V
 */

JNIEXPORT void JNICALL Java_org_ogre4j_Log_00024Stream_00024Flush__1_1delete (
  JNIEnv* _jni_env_, /* interface pointer */
  jobject _jni_this_, /* Java object */
  jlong _jni_pointer_ /* C++ pointer */
)
{
   // destructor of class Ogre::Log::Stream::Flush 
   // cast pointer to C++ object 
   Ogre::Log::Stream::Flush* _cpp_this = reinterpret_cast<Ogre::Log::Stream::Flush*>(_jni_pointer_); 
   // delete object if it exists 
   if(_cpp_this != NULL) delete _cpp_this;
} /* Ogre::Log::Stream::Flush::__delete */
