/**
 *  This source file is generated by XBiG (The XSLT Bindings Generator)
 *  For the latest info, see http://sourceforge.net/projects/xbig/
 * 
 *  Copyright (c) 2004-2008 NetAllied Systems GmbH, Ravensburg. All rights reserved.
 *  Also see acknowledgements in Readme.html
 * 
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU Lesser General Public License as published by the Free Software
 *  Foundation; either version 2 of the License, or (at your option) any later
 *  version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public License along with
 *  this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 *  Place - Suite 330, Boston, MA 02111-1307, USA, or go to
 *  http://www.gnu.org/copyleft/lesser.txt.
 * 
 *  Machine generated file
 */

        

package org.ogre4j;


import org.xbig.base.*;
public class Ray extends org.xbig.base.NativeObject implements org.ogre4j.IRay {
static { System.loadLibrary("ogre4j");}
 
        
	/**
	 * 
	 * This constructor is public for internal useage only!
	 * Do not use it!
	 * 
	 */
	public Ray(org.xbig.base.InstancePointer p) {
		super(p);
	}

	/**
	 * 
	 * Creates a Java wrapper object for an existing C++ object.
	 * If remote is set to 'true' this object cannot be deleted in Java.
	 * 
	 */
	protected Ray(org.xbig.base.InstancePointer p, boolean remote) {
		super(p, remote);
	}

    /**
     * Allows creation of Java objects without C++ objects.
     * 
     * @see org.xbig.base.WithoutNativeObject
     * @see org.xbig.base.INativeObject#disconnectFromNativeObject()
     */
	public Ray(org.xbig.base.WithoutNativeObject val) {
		super(val);
	}

	public void delete() {
		if (this.remote) {
	       throw new RuntimeException("can't dispose object created by native library");
	    }

		if(!this.deleted) {
		    __delete(object.pointer);
		    this.deleted = true;
		   	this.object.pointer = 0;
		}
	}

	public void finalize() {
		if(!this.remote && !this.deleted) {
			delete();
		}
	}
	
			
	private final native void __delete(long _pointer_);	



          /** **/
    public Ray() {
         super( new org.xbig.base.InstancePointer(__createRay()), false);
    }

    private native static long __createRay();

    /** **/
    public Ray(org.ogre4j.IVector3 origin, org.ogre4j.IVector3 direction) {
         super( new org.xbig.base.InstancePointer(__createRay__Vector3RVector3R( origin.getInstancePointer().pointer,  direction.getInstancePointer().pointer)), false);
    }

    private native static long __createRay__Vector3RVector3R(long origin, long direction);

    /** 
    Sets the origin of the ray. **/
    public void setOrigin(org.ogre4j.IVector3 origin) {
        _setOrigin__Vector3R(this.object.pointer, origin.getInstancePointer().pointer);
    }

    private native void _setOrigin__Vector3R(long _pointer_, long origin);

    /** 
    Gets the origin of the ray. **/
    public org.ogre4j.IVector3 getOrigin() {
         return new org.ogre4j.Vector3(new InstancePointer(_getOrigin_const(this.object.pointer)));
    }

    private native long _getOrigin_const(long _pointer_);

    /** 
    Sets the direction of the ray. **/
    public void setDirection(org.ogre4j.IVector3 dir) {
        _setDirection__Vector3R(this.object.pointer, dir.getInstancePointer().pointer);
    }

    private native void _setDirection__Vector3R(long _pointer_, long dir);

    /** 
    Gets the direction of the ray. **/
    public org.ogre4j.IVector3 getDirection() {
         return new org.ogre4j.Vector3(new InstancePointer(_getDirection_const(this.object.pointer)));
    }

    private native long _getDirection_const(long _pointer_);

    /** 
    Gets the position of a point t units along the ray. **/
    public void getPoint(org.ogre4j.IVector3 returnValue, float t) {
          returnValue.delete();
  returnValue.setInstancePointer(new InstancePointer(_getPoint__Realv_const(this.object.pointer, t)), false);
    }

    private native long _getPoint__Realv_const(long _pointer_, float t);

    /** 
    Gets the position of a point t units along the ray. **/
    public void operatorMultiplication(org.ogre4j.IVector3 returnValue, float t) {
          returnValue.delete();
  returnValue.setInstancePointer(new InstancePointer(_operatorMultiplication__Realv_const(this.object.pointer, t)), false);
    }

    private native long _operatorMultiplication__Realv_const(long _pointer_, float t);

    /** 
    Tests whether this ray intersects the given plane. **/
    public void intersects(org.std.Ipair< Boolean, Float > returnValue, org.ogre4j.IPlane p) {
          returnValue.delete();
  returnValue.setInstancePointer(new InstancePointer(_intersects__PlaneR_const(this.object.pointer, p.getInstancePointer().pointer)), false);
    }

    private native long _intersects__PlaneR_const(long _pointer_, long p);

    /** 
    Tests whether this ray intersects the given plane bounded volume. **/
    public void intersects(org.std.Ipair< Boolean, Float > returnValue, org.ogre4j.IPlaneBoundedVolume p) {
          returnValue.delete();
  returnValue.setInstancePointer(new InstancePointer(_intersects__PlaneBoundedVolumeR_const(this.object.pointer, p.getInstancePointer().pointer)), false);
    }

    private native long _intersects__PlaneBoundedVolumeR_const(long _pointer_, long p);

    /** 
    Tests whether this ray intersects the given sphere. **/
    public void intersects(org.std.Ipair< Boolean, Float > returnValue, org.ogre4j.ISphere s) {
          returnValue.delete();
  returnValue.setInstancePointer(new InstancePointer(_intersects__SphereR_const(this.object.pointer, s.getInstancePointer().pointer)), false);
    }

    private native long _intersects__SphereR_const(long _pointer_, long s);

    /** 
    Tests whether this ray intersects the given box. **/
    public void intersects(org.std.Ipair< Boolean, Float > returnValue, org.ogre4j.IAxisAlignedBox box) {
          returnValue.delete();
  returnValue.setInstancePointer(new InstancePointer(_intersects__AxisAlignedBoxR_const(this.object.pointer, box.getInstancePointer().pointer)), false);
    }

    private native long _intersects__AxisAlignedBoxR_const(long _pointer_, long box);

}
